# Generated by Django 5.2.4 on 2026-05-27 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la collection')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description poétique')),
                ('image_path', models.CharField(max_length=255, verbose_name="Chemin de l'image (statique)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Est active')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la pièce')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description du produit')),
                ('details', models.TextField(help_text='Séparez les lignes par des sauts de ligne', verbose_name='Matières & Entretien')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (€)')),
                ('image_path', models.CharField(max_length=255, verbose_name="Chemin de l'image (statique)")),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant (accueil)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Collection')),
            ],
            options={
                'verbose_name': 'Pièce de mode',
                'verbose_name_plural': 'Pièces de mode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('message', models.TextField(verbose_name='Message / Demande')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catalog.product', verbose_name='Pièce concernée')),
            ],
            options={
                'verbose_name': "Demande d'information",
                'verbose_name_plural': "Demandes d'information",
                'ordering': ['-created_at'],
            },
        ),
    ]
